= bespoke-nav-kbd
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
ifdef::env-github[:badges:]
// Variables:
:release-version: master
// URIs:
:uri-raw-file-base: https://raw.githubusercontent.com/opendevise/bespoke-nav-kbd/{release-version}

ifdef::badges[]
//image:https://img.shields.io/npm/v/bespoke-nav-kbd.svg[npm package, link=https://www.npmjs.com/package/bespoke-nav-kbd]
image:https://img.shields.io/travis/opendevise/bespoke-nav-kbd/master.svg[Build Status (Travis CI), link=https://travis-ci.org/opendevise/bespoke-nav-kbd]
endif::[]

Adds keyboard (kbd) navigation to a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.

== Example

http://opendevise.github.io/bespoke-nav-kbd[View the demo] online.

This repository includes a demo folder the shows this plugin in action.
To view it locally, you first need to clone this repository:

 $ git clone https://github.com/opendevise/bespoke-nav-kbd && cd bespoke-nav-kbd

Next, install the dependencies inside the project folder using npm:

 $ npm install

Finally, visit the file [path]_demo/index.html_ in your browser to see the plugin in action.

== Download

Download the {uri-raw-file-base}/dist/bespoke-nav-kbd.min.js[production mode version] or the {uri-raw-file-base}/dist/bespoke-nav-kbd.js[development mode version], or use a package manager.

=== npm

 $ npm install bespoke-nav-kbd

=== Bower

 $ bower install bespoke-nav-kbd

== Usage

This plugin is shipped in a https://github.com/umdjs/umd[UMD format], meaning it is available as a CommonJS/AMD module or as a browser global.

For example, when using CommonJS modules:

```js
var bespoke = require('bespoke'),
  navkbd = require('bespoke-nav-kbd');

bespoke.from('.deck', [
  navkbd()
]);
```

When using a browser global:

```js
bespoke.from('.deck', [
  bespoke.plugins.navkbd()
]);
```

== Credits

This plugin is a fork of the official https://github.com/markdalgleish/bespoke-keys[bespoke-keys] plugin.
This fork adds additional key bindings, does not capture events if a modifier key is pressed (except Shift + Space), has working tests and provides a cleanup routine.
It is also more clearly named.

== License

http://en.wikipedia.org/wiki/MIT_License[MIT License]
